### ISSUE TITLE
NameError: name 'time' is not defined

### ISSUE THREAD

**Issue by danfergo** [danfergo/yarok#3]
**Problem:** 
```
Traceback (most recent call last):
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/danfergo/Projects/manytasks/tasks/geltip_pick_and_place.py", line 320, in <module>
    geltip_pick_and_place()
  File "/home/danfergo/Projects/manytasks/tasks/geltip_pick_and_place.py", line 292, in geltip_pick_and_place
    Platform.create({
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/core/platform.py", line 77, in create
    return platform_class(manager, env_config, behaviour)
  File "/hoals, None,
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/danfergo/Projects/manytasks/tasks/geltip_pick_and_place.py", line 320, in <module>
    geltip_pick_and_place()
  File "/home/danfergo/Projects/manytasks/tasks/geltip_pick_and_place.py", line 292, in geltip_pick_and_place
    Platform.create({
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/core/platform.py", line 77, in create
    return platform_class(manager, env_config, behaviour)
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/platforms/mjc/platform.py", line 43, in __init__
    super(PlatformMJC, self).__init__(manager, config, behaviour)
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/core/platform.py", line 19, in __init__
    self.plugins = [self.init_plugin(pl_tuple) for pl_tuple in env_config['plugins']]
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/core/platform.py", line 19, in <listcomp>
    self.plugins = [self.init_plugin(pl_tuple) for pl_tuple in env_config['plugins']]
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/core/platform.py", line 34, in init_plugin
    return plugin_cls(**injector.get_all(init_annotations))
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/comm/plugins/cv2_waitkey.py", line 12, in __init__me/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/platforms/mjc/platform.py", line 43, in __init__
    super(PlatformMJC, self).__init__(manager, config, behaviour)
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/core/platform.py", line 19, in __init__
    self.plugins = [self.init_plugin(pl_tuple) for pl_tuple in env_config['plugins']]
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/core/platform.py", line 19, in <listcomp>
    self.plugins = [self.init_plugin(pl_tuple) for pl_tuple in env_config['plugins']]
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/core/platform.py", line 34, in init_plugin
    return plugin_cls(**injector.get_all(init_annotations))
  File "/home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/comm/plugins/cv2_waitkey.py", line 12, in __init__
    self.next_probe_ts = time.time()
NameError: name 'time' is not defined
```

**Solution**

```
nano /home/danfergo/miniconda3/envs/manytasks/lib/python3.10/site-packages/yarok/comm/plugins/cv2_waitkey.py
# import time

```

**Comment by danfergo** [comment]
replace
cv2.waitKey(self.config['ms'] or 1)
to 
cv2.waitKey(self.wait_ms)
